baseURL = 'https://moonsoochang.github.io'
languageCode = 'ko-kr'
title = 'My New Hugo Site'
theme = "PaperMod"
enableRobotsTXT = true

[params]
  defaultContentLanguage = "ko"
  showReadingTime = true
  enableSearch = true
  highlightSytle = "monokai"
  highlightLineNos = true

[menu]
  [[menu.main]]
    name = "TIL"
    url = "/til/"
    weight = 1

  [[menu.main]]
    name = "Book Review"
    url ="/books/"
    weight = 2
